web2:
  build: ./web
  ports:
    - "8080:8080"
  volumes:
    - ./code:/code
  links:
    - mysql:db-bottle

mysql:
  container_name: db-bottle
  image: mysql
  volumes:
   - ./initdb.d:/docker-entrypoint-initdb.d
  environment:
    MYSQL_ROOT_PASSWORD: password
    MYSQL_USER: python
    MYSQL_PASSWORD: python
    MYSQL_DATABASE: sample
  ports:
    - "3306:3306"
